# fly.toml file generated for rchab on 2021-01-08T16:05:33-05:00

app = "rchab"

kill_signal = "SIGINT"
kill_timeout = 5

[[mounts]]
source = "data"
destination = "/data"

[[services]]
internal_port = 8080
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20

[[services.ports]]
handlers = []
port = "80"

[[services.ports]]
handlers = ["tls"]
port = "443"

[[services.tcp_checks]]
interval = 10000
timeout = 2000

[env]
ALLOW_ORG_SLUG = "fly"
